site_name: AI for Robotics Course
site_description: A course on AI for robotics by SMART Mechatronics and Robotics Group, Saxion University of Applied Sciences
site_author: Stephan Jaspar, Rahul Moongayil Ramakrishnan, Kousheek Chakraborty

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

plugins:
  - search
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
      widgets: false
  - mcq

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Foundations:
      - Introduction to robotics: foundations/Introduction_to_robotics.md
      - Introduction to artificial intelligence: foundations/introduction_to_ai.md
      - AI helping robotics: foundations/combine_ai_and_robotics.md
      - Challenges in AI for robotics: foundations/Challenges_in_ai_for_robotics.md
      - Introduction to deep learning:
        - foundations/why_start_with_deep_learning.md
        - foundations/introduction_to_deep_learning.md
      # - Practical Tutorial: Foundations/practical_tutorial.md
  - Deep Learning:
      - deep_learning/index.md
      - Introduction to Git | Python 101 | Pytorch 101: deep_learning/0_Git_Python_Pytorch.md
      - Introduction to Deep Learning: deep_learning/12_Introduction.md
      - Model Setup: deep_learning/1_Code.md
      - Quiz 1: deep_learning/1_mcq.md
      - Model Skeleton: deep_learning/2_Code.md
      - Quiz 2: deep_learning/2_mcq.md
      - Lighter Model: deep_learning/3_Code.md
      - Quiz 3: deep_learning/3_mcq.md
      - Batch Normalization Integration: deep_learning/4_Code.md
      - Quiz 4: deep_learning/4_mcq.md
      - Regularization: deep_learning/5_Code.md
      - Quiz 5: deep_learning/5_mcq.md
      - Global Average Pooling: deep_learning/6_Code.md
      - Quiz 6: deep_learning/6_mcq.md
      - Increasing Model Capacity: deep_learning/7_Code.md
      - Quiz 7: deep_learning/7_mcq.md
      - Correcting MaxPooling Location: deep_learning/8_Code.md
      - Quiz 8: deep_learning/8_mcq.md
      - Image Augmentation: deep_learning/9_Code.md
      - Quiz 9: deep_learning/9_mcq.md
      - Learning Rate Scheduling: deep_learning/10_Code.md
      - Quiz 10: deep_learning/10_mcq.md
      - Summary: deep_learning/11_Summary.md
      - Quiz: deep_learning/mcq.md
      - Backward Propagation: deep_learning/Backward_Propagation.md

  - Reinforcement Learning:
      - reinforcement_learning/index.md
      - Introduction to RL: reinforcement_learning/1_introduction.md
      - Quiz 1: reinforcement_learning/1_quiz.md
      - Markov Decision Processes: reinforcement_learning/2_mdp.md
      - Quiz 2: reinforcement_learning/2_quiz.md
      - Policy vs Value-Based: reinforcement_learning/3_policy_vs_value.md
      - Quiz 3: reinforcement_learning/3_quiz.md
      - Q-Learning: reinforcement_learning/4_value_based.md
      - Policy Gradients (REINFORCE): reinforcement_learning/5_policy_based.md
      - Practical Tutorial: reinforcement_learning/6_practical_tutorial.md
  - Resources: resources.md


